name: desing_ipscamv2
description: Un nuevo proyecto de Flutter.
# La siguiente línea evita que el paquete se publique accidentalmente en
# pub.dev utilizando `flutter pub publish`. Esto es preferible para paquetes privados.
publish_to: "none" # Elimina esta línea si deseas publicar en pub.dev

# Lo siguiente define la versión y el número de compilación para tu aplicación.
# Un número de versión consta de tres números separados por puntos, como 1.2.43,
# seguido de un número de compilación opcional separado por un +.
# Tanto la versión como el número de compilación se pueden anular en flutter
# build especificando --build-name y --build-number, respectivamente.
# En Android, build-name se utiliza como versionName, mientras que build-number se utiliza como versionCode.
# Lee más sobre la versión de Android en https://developer.android.com/studio/publish/versioning
# En iOS, build-name se utiliza como CFBundleShortVersionString, mientras que build-number se utiliza como CFBundleVersion.
# Lee más sobre la versión de iOS en
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# En Windows, build-name se utiliza como las partes de mayor, menor y corrección
# de las versiones de producto y archivo, mientras que build-number se utiliza como sufijo de compilación.
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

# Las dependencias especifican otros paquetes que necesita tu paquete para funcionar.
# Para actualizar automáticamente las dependencias de tu paquete a las últimas versiones,
# considera ejecutar `flutter pub upgrade --major-versions`. Alternativamente,
# las dependencias se pueden actualizar manualmente cambiando los números de versión a continuación
# a la última versión disponible en pub.dev. Para ver qué dependencias tienen versiones más recientes disponibles,
# ejecuta `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # Lo siguiente agrega la fuente de iconos Cupertino Icons a tu aplicación.
  # Úsalo con la clase CupertinoIcons para iconos de estilo iOS.
  cupertino_icons: ^1.0.2

  google_mlkit_text_recognition: ^0.10.0
  image_picker: ^1.0.2
  image_cropper: ^5.0.0

  connectivity: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # El paquete "flutter_lints" a continuación contiene un conjunto de lints recomendados
  # para fomentar buenas prácticas de codificación. El conjunto de lints proporcionado por el paquete
  # se activa en el archivo `analysis_options.yaml` ubicado en la raíz de tu paquete.
  # Consulta ese archivo para obtener información sobre cómo desactivar lints específicos
  # y activar otros adicionales.

  flutter_lints: ^2.0.0

# Para obtener información sobre la parte genérica de Dart de este archivo, consulta la
# siguiente página: https://dart.dev/tools/pub/pubspec

# La siguiente sección es específica para paquetes Flutter.
flutter:
  # La siguiente línea asegura que la fuente de iconos Material Icons esté
  # incluida en tu aplicación, para que puedas usar los iconos en
  # la clase Material Icons.
  uses-material-design: true

  assets:
    - assets/images/
  # Para agregar recursos a tu aplicación, agrega una sección de assets, como esta:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Un recurso de imagen puede hacer referencia a una o más "variantes" específicas de resolución, consulta
  # https://flutter.dev/assets-and-images/#resolution-aware para obtener detalles

  # Para obtener detalles sobre cómo agregar recursos de paquetes de dependencias, consulta
  # https://flutter.dev/assets-and-images/#from-packages

  # Para agregar fuentes personalizadas a tu aplicación, agrega una sección de fuentes aquí,
  # en esta sección "flutter". Cada entrada en esta lista debe tener una
  # clave "family" con el nombre de la familia de fuentes y una clave "fonts" con una
  # lista que indique el recurso y otros descriptores de la fuente. Por ejemplo:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  # Para obtener detalles sobre las fuentes de paquetes de dependencias,
  # consulta https://flutter.dev/custom-fonts/#from-packages
